server:
  bind-address: "$BIND_ADDRESS"
  dns-forward: "$DNS_FORWARD"
  http-server: "$HTTP_BINDADDRESS"

networks:
  private:
    ipv4: "$DEFAULT_IPV4_CIDR"
    ipv6: "$DEFAULT_IPV6_CIDR"

actions:
  PROXY:
    method: "fakeip"
    fakeip-release-delay: 600
    ttl:
      max-transfer: 120
      min_rewrite: 100
      max_rewrite: 300
    dns-forward: "$DNS_FORWARD"
    variable:
      wan: "$IFACE"
      mark: "PROXY"
      tname: "$TNAME_NAT"
      nets: "$INSTALLTYPE"
    fakeip-networks:
        - "private"
    script:
      add: "sh sh/add.sh {fakeIP_private} {realIP} {mark} {wan} {tname}"
      delete: "sh sh/delete.sh {fakeIP_private} {realIP} {mark} {wan} {tname}"
      onreset: "sh sh/onReset.sh {tname} {nets}"
      onstart: "sh sh/onStart.sh {tname}"